services:
  blog-database:
    image: mongo
    ports:
      - '27018:27017'
  blog-backend:
    build: backend/
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://host.docker.internal:27018/blog
    ports:
      - '3000:3000'
    depends_on:
      - blog-database
  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3000/api/v1
    ports:
      - '5173:80'
    depends_on:
      - blog-backend
